# Generated by Django 5.2.15 on 2026-07-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
